language: node_js
node_js:
 - 7.4.0
sudo: required
services:
- docker

before_script:
- npm install -g gulp
script:
- gulp default
after_success:
- scripts/travis-publish.sh
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - secure: "Ybysjlyws3GW0t/yHSAtFz5/wBza+FuzsUru+gXsRrLJBIjF2OpI/1/fqGWkMKHVhQICnAvGnQPm4ZtF0JroBlp6gQatJgQh5qngvlCck8fJaYJId6MPDXGixlWBoLuXMrSQLHY2RHKnAyIq3MpBV1KaNK8G8gozeWkWP9l/+zba98Xh/duDzWqM/GUl3lz9IuoWw0NHJnaV3Tt6/pT5QB1b2L7ZEYM3p+NL13PWexWP3yompBELdT3kr3vk1/r3M9oD+BL2G6MVaZeNV1JKw2Vyrf30T7m+rdXfgfXEHmt1YUEtOe9Njzp8D7doiwkxBPi21w76QK1t4kVvG5dn+J4eWJMMfCZmtdPozdFkmOunBHcnO0OiZWQ9HYGS/uaAeOIAoKGo7dvt1Q1VRdnTenl9Tyb2c8q4gYv1rrcDUZG57YQz/z7XURtf6tbQIFOlm1O7gB6bzDlQ+jtsb2g8jGkwZMFVmGYabmJ8GSaVbMCbord+GeRVer3Gs69jyYCyV5QC5/DOyT/6WwN215k2Mree3faA7Ro6w0VcxguxIDCsbvTQh3J6WVqm5X/jluF8dTXbEH2vsPOGeMuPLixWTitOXmzJJecSypBeYgO/LYNdbwjy9vp/+lYQBEo/GQGXuHXX8FriCcQKTrK7foayFe3DWiRte2SK6Wc4RjhJncA="
